### ISSUE TITLE
Research dynamic NPM library integration

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/builder#1696]
Users may want to integrate third party NPM libraries that we have not provided. See if this is possible & how we would achieve it. Explain the architecture & the steps we would need to take to get there.

**Comment by antonmihaylov** [comment]
Npm packages are on https://unpkg.com. We could include a script tag pointing to it and it will be globally available.

## Idea 1 - unpkg + Script tags

We would add a "packages" field to App. Each Package consists of:
- Npm identifier (e.g. `jquery`)
- Version - optional, semver-style - used if the user wants to pin a specific version. (e.g. ~2.0.0, ^18, etc.)
- Filename - optional, a specific file to be included. This is usually not needed, because by default Unpkg includes the default file, usually the "main" in package.json. But sometimes it's needed, see the example bellow
- ScriptOptions - optional, props that will get passed to the <Script/> tag - for example `strategy`
- StateKey - optional, the result of the package import will be assigned to globalState[stateKey]. This is useful for ESM packages, or in general - ones that don't define global variables. For example, packages like axios or jquery would work fine without this because you could access them anywhere using their global identifiers - `axios` and `$`. But for example, firebase wouldn't work, because you have to import and use it locally - see the example below.

The user flow would look like this:
- User adds a new package to their app:
    -  identifier: "firebase"
    -  version: "^9"
    - file: firebase-app.js
    - stateKey: fb
- The file is needed because you don't normally do `import x from firebase`, but `import app from firebase/app`. The exact file name is in their readme https://www.npmjs.com/package/firebase
- The packages are passed down to the renderer
- The renderer renders a different  [<Script/>](https://nextjs.org/docs/basic-features/script) tag depending on StateKey.
    - If there's not state key, render:  A <Script/> tag with its source being `unpkg.com/:package@:version`, or `unpkg.com/:package` if the version is missing
    -  If the state key is present, render:
```js
<Script
   type="module"
    dangerouslySetInnerHTML={{
    __html: `
        // scriptUrl, in that case, would be unpkg.com/firebase/firebase-app.js
        import lib from '${scriptUrl}';
        window.globalStateInit  = window.globalStateInit || {}
        window.globalStateInit["${stateKey}"] = lib
    `,
  }}
/>
```
- When we initialize the global state we would look at window.globalStateInit and assign each key to a state variable. For example in that case we would assign `state["fb"] = window.globalStateInit["fb"]`
- Additionally, we can let the user define a `onInit` action that we will call whenever we first initialize the state. The user would create a `onInit` action like anything else and in it they can initialize firebase for example:
```
// on init action:
this.firestore = this.fb.getFirestore(app)
```
- The user will be able to use the imported library in all actions

Pros:
- It's simple for the user - just add a package and start using it
- It feels more integrated with the platform
Cons:
- I'm not sure if the `import lib from '${scriptUrl}'` will work for all libraries, we have to make a PoC


## Idea 2 - custom script tag

Add a user-defined script block in the App (or in separate Pages). In it the user can import anything from anywhere they want to.

It's not exactly npm packages, but most offer a CDN version and if they don't - we can suggest to the user to use a unpkg link

For example, if the user wants to use Firebase they would add this to app.script:
```
import { initializeApp } from 'https://www.gstatic.com/firebasejs/9/firebase-app.js';
import { getFirestore, collection, getDocs } from 'https://www.gstatic.com/firebasejs/9firebase-firestore-lite.js';
    
const firebaseConfig = {
    //...
};

const app = initializeApp(firebaseConfig);
    
// Assign it to a window variable so that it's useable in state actions
window.db = getFirestore(app);


// With a bit more imagination this coul be integrated with the global state
// For example, if the users sets:
window.globalStateInit.firebase = getFirestore(app)
// We could later read that and assign window.globalStateInit.firebase to globalState.firebase

```
- This script would be rendered using a <Script type="module" dangerouslySetInnerHTML={{_html: app.script}}/>
- We could again add script props. 
- We could make it an array of scripts so that the user can define multiple scripts with different loading strategies.

Pros:
- Allows full customizability
Cons:
- Feels like we just leave the user to their own devices, it's not as integrated as the other option

**Comment by webberwang** [comment]
To take it one step further, would it be possible for a user to create their own atom?

**Comment by antonmihaylov** [comment]
Doesn't seem farfetched. If they write a script, use `export default Component`, assign it an atom type. We can eval it, use the default export and pass it to the renderer. I'm just not sure how imports and eval play together, we have to test that

**Comment by assimhabeek** [comment]
npm packages, are of three types. pure ES6 / pure CommenJs   / supporting both ES6 and CommenJs :

### Pure CommentJS packages : 
 - Doesn't support `import` statement,  `import x from `https://unpkg.com/[package]`
 - Support `script` tag, user could use `https://unpkg.com` or CDN of their choice, `<script src="url" ></script>`  
 - No need to pass to global scope `window`. user will be able to access package globally by name.
 
### Pure ES6 packages :
 - Support import/export. (the only why to use it)
 - Doesn't support script tag importing with `src` attribute as its content is inaccessible this way.
 - Need to manually pass to global scope 
 
 ###  Supporting both ES6 and CommenJs 
When are available user will have an option of which approach to use


## Proposed  Solution 
Two approaches were proposed by @antonmihaylov  to chose from, but indeed we need them both in addition to @webberwang  suggestion to use atoms. we need to add only one atom. a wrapper for NextJS script tag. the user will user script tag like he used to. 

1- By importing `<script src="url" ></script>`  for CommentJS packages


2- By pass small portion of code to `innerHtml` field prop for the script atom 
 ```
import { lib } from 'my-lib-url';
window.mylib = lib
```

### Side notes

This scripts will be treated as any other atom in terms of api. attributes like `file-version` and so on doesn't appear on the api, but instead the will be visible on the `src`

### Test out things : 1696-dynamic-integration

### Demo : coming soon
