### ISSUE TITLE
Cypress seed refactor

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/builder#1771]
## Current implemenation

We currently use specific graphql requests to add data, for example we would call the atom or app api for CRUD.

Instead, we could use the execute command api to send a cli command to seed data. Each spec would have a seed file with data that it requires.

## Disadvantages

- Could be harder to write up a seed file. Would either have to code it manually, or create the UI and export.

## Advantages

- Keeps the Cypress file much cleaner, require only a single API request to speed up the seed steps.
- Allow us to test our seeder at the same time (this could be seen as a disadvantage as well, since requires updates to our seeder)

**Comment by antonmihaylov** [comment]
That's making the tests more complex and harder to read, write and maintain. In my opinion having the cypress file clearer is not much of a benefit since it would be harder to trace where the data is coming from and exactly what are you seeding. For example, I imagine you'd want to seed different data in different tests, which could get complex fast.
As for testing the seeder - this can always be done separately

**Comment by webberwang** [comment]
Yeah I do agree with that
